# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  #imports =
  #  [ (modulesPath + "/installer/scan/not-detected.nix")
  #  ];

  boot.initrd.availableKernelModules = [ "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = [ "snd_bcm2835.enable_headphones=1" ];
  boot.blacklistedKernelModules = [ "vc4_hdmi" ];

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-label/FIRMWARE";
      fsType = "vfat";
    };
    "/swap" = {
      device = "/dev/disk/by-uuid/SWAP";
      fsType = "btrfs";
      options = [ "subvol=swap" "compress=lzo" "noatime" ]; # Note these options effect the entire BTRFS filesystem and not just this volume, with the exception of `"subvol=swap"`, the other options are repeated in my other `fileSystem` mounts
    };
    "/" = {
      device = "/dev/disk/by-label/NIXOS_SD";
      fsType = "ext4";
    };
  };

  swapDevices = [{
    device = "/swap/swapfile";
    size = (1024 * 2);
  }];

  hardware.enableRedistributableFirmware = true;
  #networking.wireless.enable = true;
  boot.loader.raspberryPi.firmwareConfig = ''
    gpu_mem=192
    dtparam=audio=on
  '';

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}

